version: '3'
services:
  postgres:
    image: postgres
    container_name: postgres
    network_mode: "host"
    env_file:
      - database.env
    volumes:
      - ./postgres/postgres_data:/var/lib/postgresql/data/

  back:
    image: kozinoleg97/saturn_back
    container_name: backend
    network_mode: "host"
    depends_on: postgres

  front:
    image: kozinoleg97/saturn_front
    container_name: frontend
    network_mode: "host"
    depends_on: back

